server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: picture-service
          uri: http://picture-service-app:8085
          predicates:
            - Path=/api/v1/picture/**
        - id: shop-backend-api
          uri: http://shop-backend-api-app:8081
          predicates:
            - Path=/api/v1/**
        - id: shop-backend-api-ws
          uri: ws://shop-backend-api-app:8081
          predicates:
            - Path=/api/v1/**
