FROM nginx:latest

RUN mkdir -p /var/www/html
RUN chown -R $USER:$USER /var/www/html
RUN chmod -R 755 /var/www/
# RUN mkdir -p /etc/nginx/sites-available
RUN rm /etc/nginx/conf.d/default.conf
COPY ./dist/shop-frontend-app/* /var/www/html/
COPY ./nginx-conf /etc/nginx/conf.d/default.conf

